// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class RealEstatePlatform_Model
{
    /// <summary>
    /// model input class for RealEstatePlatform_Model.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(0)]
        [ColumnName(@"price")]
        public float Price { get; set; }

        [LoadColumn(1)]
        [ColumnName(@"bedrooms")]
        public float Bedrooms { get; set; }

        [LoadColumn(2)]
        [ColumnName(@"bathrooms")]
        public float Bathrooms { get; set; }

        [LoadColumn(3)]
        [ColumnName(@"sqft_living")]
        public float Sqft_living { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for RealEstatePlatform_Model.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"price")]
        public float Price { get; set; }

        [ColumnName(@"bedrooms")]
        public float Bedrooms { get; set; }

        [ColumnName(@"bathrooms")]
        public float Bathrooms { get; set; }

        [ColumnName(@"sqft_living")]
        public float Sqft_living { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"Score")]
        public float Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("RealEstatePlatform.Model.mlnet");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }

}
